server {
    listen 9443 ssl;
    server_name localhost;

    ssl_certificate /home/jimi/tesi-ebpf/nginxTest/nginx-zap.crt;
    ssl_certificate_key /home/jimi/tesi-ebpf/nginxTest/nginx-zap.key;

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
